name: CICD

on:
  push:
    branches: [develop]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source.
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
      - name: Build Project
        run: mvn clean install -DskipTests
      
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t sujanabandari19/usermanagement-service:latest .

      - name: Push Docker image to Docker Hub
        run: docker push sujanabandari19/usermanagement-service:latest

      - name: SSH into EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ~/.ssh/id_rsa
          port: 22
          script: |
            docker pull sujanabandari19/usermanagement-service:latest
            docker run -d -p 8080:8080 sujanabandari19/usermanagement-service:latest
