name: CICD

on:
  push:
    branches: [develop]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
      - name: Build Project
        run: mvn clean install -DskipTests
      - name: Login to Docker hub
        run: docker login -u username -p password
